### ISSUE TITLE
Constantly moving slider back and forth breaks clipping rectangle in swipe layers example

### ISSUE THREAD

**Issue by nextstopsun** [mapbox/mapbox.js#1093] opened 2015-12-09 11:21 UTC
When zooming out and then moving slider back and forth, at some point clipping rectangle becomes unresponsive 
https://www.mapbox.com/mapbox.js/example/v1.0.0/swipe-layers/

Tested on OS X in Chrome 47.0.2526.73 and Safari 11601.2.7.2 
Here's how it looks like:
![Broken range](https://www.dropbox.com/s/k0mfc250fddtffj/Screen%20Shot%202015-12-09%20at%2013.57.25.png?dl=1)

**Comment by jfirebaugh** [comment] 2015-12-09 18:14
Duplicate of #911.

**Closed as completed by jfirebaugh** 2015-12-09 18:14 UTC
