### ISSUE TITLE
400 Error for Aerialway and Dentist Icons

### ISSUE THREAD

**Issue by che-wf** [mapbox/mapbox.js#1045] opened 2015-07-25 17:42 UTC
I'm currently trying to pull the dentist and aerialway icons. I've used Maki to display all of the icons, however, I'm getting a `400 (Bad Request)` error whenever I try to use the icons on a marker although the rest of my icons are all pulling correctly. 

My requests are `http://a.tiles.mapbox.com/v4/marker/pin-m-dentist+739.png?access_token=[my token]` and `http://a.tiles.mapbox.com/v4/marker/pin-m-aerialway+739.png?access_token=[my token]`.

The response I'm getting is `{"message":"Marker \"pin-m-dentist+739\" is invalid."}`.

Obvsiously, I realize that this is saying that this marker is not valid. However, I was under the impression that all of the icons used in Maki were available as icons for Mapbox.

**Comment by jfirebaugh** [comment] 2015-08-05 15:30
Hi @jbcoder, sorry about the confusion here. The dentist and aerialway icons are the two icons that were most recently added to maki, so likely the issue is that our markers API hasn't been updated to the latest maki version.

@lyzidiamond is this something you could look into?

**Comment by lyzidiamond** [comment] 2015-08-05 17:21
@jfirebaugh sure! @jbcoder I will take a look and get back to you.

**Comment by che-wf** [comment] 2015-08-06 01:18
You guys are awesome!

**Comment by lyzidiamond** [comment] 2015-08-06 23:07
Hey @jbcoder, fixing this is going to take a little while -- what started as a simple inquiry is going to require a somewhat-involved process! I'll update here when the issue is resolved. In the meantime, thanks for your patience!

**Comment by lyzidiamond** [comment] 2015-10-07 18:59
@jbcoder this should be fixed now with a new release of Maki! Let us know if you're having any other issues.

**Closed as completed by lyzidiamond** 2015-10-07 18:59 UTC
