### ISSUE TITLE
IE9 jsonp (?) issues

### ISSUE THREAD

**Issue by lxbarth** [mapbox/mapbox.js#134] opened 2012-10-29 22:53 UTC
I'm observing 2 likely related issues w/ mapbox.js HEAD and IE9 (9.0.8112):
1. mapbox.load() sporadically returning an empty tilejson object
2. interactivity dead where MapBox hosting returns 304 (not modified)
## Example
- http://mapbox.com/frame/?villeda.map-m1aei9is#5.00/34.866/-73.903
- http://gis.nyc.gov/oem/he/map.htm (they're about to apply a fix for (1) where they'll embed the tilejson hash in the application, so issue 2 should be nicely observable there).

I cannot reproduce these issues with an older setup, e. g.:

http://www.npr.org/censusmap/#6.00/41.152/-90.943

**Comment by lxbarth** [comment] 2012-10-29 22:56
Possibly related #127

**Comment by gundersen** [comment] 2012-10-29 23:09
@tmcw how much of our subscribers are effected by this? How long will it take to fix? 

@lxbarth how urgent is this for NYC?

cc @willwhite

**Comment by tmcw** [comment] 2012-10-29 23:25
I've filed a ticket for the upstream problem & re-noted it. I can't really guess how many people are affected by this, since the issues are new to me, haven't been reported in support.mapbox.com, and haven't been reported in mapbox or wax till today.

**Comment by tmcw** [comment] 2012-10-30 00:13
Does this occur in IE<9?

**Comment by dhcole** [comment] 2012-10-30 00:39
@tmcw I saw it in IE8 too, and more often.

**Comment by tmcw** [comment] 2012-10-30 00:46
@dhcole I thought your problem was related to map loading only? Did you see the other two issues alex is talking about here?

**Comment by dhcole** [comment] 2012-10-30 00:58
Yes I was specifically seeing 1) with `mapbox.load` and `mapbox.auto`.

**Comment by lxbarth** [comment] 2012-10-30 01:28
The interactivity bug described also affects MapBox hosting: http://tiles.mapbox.com/villeda/map/nyc-sandy

**Comment by willwhite** [comment] 2012-11-02 01:46
MapBox supports standard [JSONP](http://c.tiles.mapbox.com/v3/willwhite.map-mx3xcech/12/1170/1567.grid.json?callback=foobar1234567) now. The task is now to add support to mapbox.js and do a release.

**Comment by lxbarth** [comment] 2012-11-02 19:48
HOTDOG!

**Comment by tmcw** [comment] 2012-11-02 19:49
Will be able to tackle this early next week.

**Comment by gundersen** [comment] 2012-11-02 19:52
@tmcw how big of a lift is this and can @ansis help?

**Comment by ansis** [comment] 2012-11-02 23:11
@tmcw, what is it that needs to be done?
I haven't been able to reproduce either of the issues in an IE8 vm.

**Comment by tmcw** [comment] 2012-11-02 23:29
Basically:
- We need to re-test reqwest in IE8, 9, and 10. The problems got worse in 10, with people reporting that it's entirely broken (including shawn at stamen). Either fix or switch there.
- Test mapbox.js in IE9, test multiple maps on the same page, and interaction - and change the hardcoded `grid` callback in `wax.request.get` to use unique callbacks for safety.

**Comment by willwhite** [comment] 2012-11-06 17:45
@ansis what is your week looking like? Is this something you could look at?

**Comment by tmcw** [comment] 2012-11-12 17:41
@ansis any luck on this? Is anyone else in a position to take this work? It'd likely be better for me to keep on iD + Leaflet investigation rather than get pulled off onto this potentially long task.

**Comment by tmcw** [comment] 2012-11-13 21:52
@yhahn do you have time to take a look at this one? reqwest hasn't been updated in 6 months, which isn't good, but there also are no clear alternatives I'm seeing other than superagent. just using multiple callback names may fix the problem, though not sure.

**Comment by yhahn** [comment] 2012-11-14 02:13
Where we're at:
- https://github.com/mapbox/mapbox.js/tree/jsonpcallback

Updated to point at `jsonpcallback` branches of `wax` and `markers.js` that continue to use `reqwest` but with its built-in dynamic callback support. I've added a `testcase/jsonp.html` in both `master` and `jsonpcallback`.

The problems we're running into at this point are:
- Both `master` and `jsonpcallback` branches work on IE8 and IE9 with the testcase so it's not clear whether the changes actually fix anything.
- Interaction continues to be broken in IE10.

The next task on hand is to come up with a test case that is reliably broken in IE9.

**Comment by willwhite** [comment] 2012-11-14 17:31
Assigned to [Tender discussion #635](http://support.mapbox.com/discussions/mapbox-tiles/635-mapboxjs-auto-implementation-not-working-correctly-with-ie).

**Comment by willwhite** [comment] 2012-11-14 20:38
Partly addressing with ded/reqwest#89

**Comment by yhahn** [comment] 2012-11-19 17:18
This should be resolved with https://github.com/mapbox/mapbox.js/pull/139. I've rolled a `0.6.7-dev` with this fix and packaged it up here:
- http://api.tiles.mapbox.com/mapbox.js/v0.6.7-dev/mapbox.js
- http://api.tiles.mapbox.com/mapbox.js/v0.6.7-dev/mapbox.css

Would love confirmation of the fix so we can roll a `0.6.7`.

**Comment by mnoble01** [comment] 2012-11-21 01:16
Awesome, fixed the map loading issue for me in IE9. Great work!

**Closed as completed** 2012-11-25 16:39 UTC
