### ISSUE TITLE
Cannot get markers to display on map with username and id

### ISSUE THREAD

**Issue by zodthepossum** [mapbox/mapbox.js#1154] opened 2016-08-05 06:31 UTC
I've been developing a map for a community website with mapbox editor, however when I embed the map on the webpage the markers will not display on the map.

```
<div id="map"></div>
<script type="text/javascript">$(document).ready(function(){

    var mymap = L.map('map').setView([-30.1727, 151.0699], 14);

    L.tileLayer('https://api.mapbox.com/styles/v1/mapbox/satellite-v9/tiles/256/{z}/{x}/{y}?access_token=mytoken', {
        attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://mapbox.com">Mapbox</a>',
        maxZoom: 18,
        id: 'userid.projectid',
        accessToken: 'mytoken'
    }).addTo(mymap);
});
```

and added the relevant files

<link rel="stylesheet" type="text/css" href="leaflet/leaflet.css" />

<script type="text/javascript" src="leaflet/leaflet.js"></script>

<script type="text/javascript" src="leaflet/mapbox.js"></script>

Hoping you can help, have I missed anything?
zod

**Comment by tmcw** [comment] 2016-10-03 13:56
Hi Zod,

Can you link to the page you're trying to embed this in, or the software that the community website is? If this works on a normal HTML page and doesn't work on the community software, then the issue is likely something in that difference - like potentially a sanitization step or filter on the community website.
- Tom

**Comment by tmcw** [comment] 2017-02-07 16:49
Closing, needed details.

**Closed as completed by tmcw** 2017-02-07 16:49 UTC
