### ISSUE TITLE
Uncaught TypeError in L.mapbox.geocoder v2.0.0

### ISSUE THREAD

**Issue by bunkat** [mapbox/mapbox.js#837] opened 2014-08-04 08:48 UTC
I just moved to version 2.0.0 of the Mapbox Javascript API and am trying to use the geocoder. I've provided my API key and switched over to using `mapbox.places-v1` for the geocoder id but now I'm getting a TypeError.

Here is how I'm calling the geocoder:

```
L.mapbox.accessToken = '<my public token>';
geocoder = L.mapbox.geocoder('mapbox.places-v1');
geocoder.query('22647 NE Redmond Fall City Rd, Redmond, WA 98053-8269', function(err, data) { }
```

And this is the exception that is being thrown:

```
Uncaught TypeError: Cannot read property 'center' of undefined 
n.features&&(o.latlng=[n.features[0].center[1],n.features[0].center[0]])
```

**Comment by jfirebaugh** [comment] 2014-08-04 16:37
Duplicate of #817 -- this has been fixed for 2.0.1.

**Closed as completed by jfirebaugh** 2014-08-04 16:37 UTC
