### ISSUE TITLE
Internet Explorer

### ISSUE THREAD

**Issue by sathishnaberly** [mapbox/mapbox.js#1155] opened 2016-08-11 05:12 UTC
HI,
We have an application in which we incorporated the Map by using Mapbox.js. 
Here is the issue which we are facing
Mapbox.js is not responding while panning and zooming in Internet explorer and Edge browsers. when we do the action fast (like keep on dragging using mouse).
Once the previous drag is finished then only it allow to drag again or zoom again.

What is the solution for this.

**Comment by tmcw** [comment] 2016-11-21 20:03
We'll need an example for this one. Most likely the issue is either with a site implementation problem, or Leaflet core.

**Comment by tmcw** [comment] 2017-02-07 16:49
Closing, needed details.

**Closed as completed by tmcw** 2017-02-07 16:49 UTC
