### ISSUE TITLE
Swipe Layers: zooming out doesn't always change composite cover

### ISSUE THREAD

**Issue by mayarichman** [mapbox/mapbox.js#73] opened 2012-07-25 15:38 UTC
![](https://img.skitch.com/20120725-dpys8a6rcn2gmwpbum1r6bn1ec.jpg)

The site can be found at http://developmentseed.org/tandale/. When I move the drag wheel at top and then zoom out, the drag wheel won't reveal more of the map but lets you still drag it.

**Comment by tmcw** [comment] 2012-07-25 19:09
Could you add more detail + a link to the site? I'm not sure what the potential bug is in this case.

**Comment by ansis** [comment] 2012-07-27 16:47
To reproduce:
- Drag to middle of map
- Zoom out
- Try dragging further, map won't update

It looks like `clip` gets sets on the level element somehow, and that this doesn't get updated on later drags (it gets set on the layer element fine).

Another report at http://support.mapbox.com/discussions/general-questions/2543-new-mapboxjs-demo-swipe-layers-seems-to-be-buggy

**Comment by ansis** [comment] 2012-07-27 21:31
This is caused by the way ModestMaps creates level elements for layers. Issue opened at https://github.com/modestmaps/modestmaps-js/issues/42

**Comment by ansis** [comment] 2012-07-30 21:28
Fixed in new MM d52266d8c8511890cfda8a1481b0052355222125

**Closed as completed by ansis** 2012-07-30 21:28 UTC
