### ISSUE TITLE
Mapbox doesn't support ES6 module syntax (or requiring to a variable)

### ISSUE THREAD

**Issue by ccapndave** [mapbox/mapbox.js#1007] opened 2015-05-20 13:39 UTC
Since the main file (`index.js`) doesn't expose a module.exports its not possible to use ES6 imports such as:

```
import L from 'mapbox.js'
```

or even

```
var L = require('mapbox.js');
```

This is a similar issue to #1003 and #725.

**Comment by tmcw** [comment] 2015-05-20 15:58
This is a duplicate of #1003

**Closed as completed** 2015-06-16 21:43 UTC
