### ISSUE TITLE
Swipe layer example breaks after zoom

### ISSUE THREAD

**Issue by geografa** [mapbox/mapbox.js#917] opened 2014-11-28 23:22 UTC
When zooming a map, swipe tool no longer works and tiles do not load properly. 
https://www.mapbox.com/mapbox.js/example/v1.0.0/swipe-layers/

**Comment by jfirebaugh** [comment] 2014-11-28 23:38
Duplicate of #911.

**Comment by geografa** [comment] 2014-11-28 23:39
:+1:

**Closed as completed by jfirebaugh** 2014-11-28 23:38 UTC
Labels: bug
