### ISSUE TITLE
Leaflet and Mapbox lib version confusion

### ISSUE THREAD

**Issue by jmoe** [mapbox/mapbox.js#907] opened 2014-11-03 21:37 UTC
What version of leaflet is mapbox.js supposed to support? package.json has 0.7.3, but calling L.version on an example page returns 0.7.2.

Further, a page that loads V 2.1.4 of mapbox.js returns 2.1.3 when L.mapbox.VERSION is called.

Example Page
https://www.mapbox.com/mapbox.js/api/v2.1.4/

**Comment by tristen** [comment] 2014-11-03 22:03
@jmoe Thanks for the heads up. Looks like I missed a deploy step here. I'll need to publish a `v2.1.5` version of mapbox.js to resolve this one.

**Comment by jmoe** [comment] 2014-11-03 22:08
Cool. Totally random that I happened on that. I was looking for a bugfix in Leaflet 0.7.3 and that got me down the rabbit whole and noticed that other stuff.

**Comment by tristen** [comment] 2014-11-03 23:27
@jmoe On second thought I think I want to hold off on a whole new deploy here. Looks like 0.7.3 of Leaflet reports `0.7.2` version key despite the code being up to date (see https://github.com/Leaflet/Leaflet/issues/2735) and the same can be said for 2.1.4 of mapbox.js; it's just the hardcoded version key thats amiss, not the code.

**Comment by tmcw** [comment] 2014-11-05 20:31
Let's keep this open until the issue is fixed, even if that means a future version bump.

**Comment by jmoe** [comment] 2014-11-05 21:26
The odd part is that a bugfix that is supposed to be in Leaflet 0.7.3 doesn't appear to work when using the leaflet being loaded by mapbox.js. Will see if I can get you more concrete evidence of that.

**Comment by jmoe** [comment] 2014-11-05 21:34
You know what, I take it back, looks like the fix I'm looking for got in 3 days after the 0.7.3 release of Leaflet, as far as I can tell.

**Comment by mourner** [comment] 2014-11-05 22:43
@jmoe what's the fix?

**Comment by jmoe** [comment] 2014-11-06 03:40
This one:

https://github.com/Leaflet/Leaflet/issues/2489 

If I'm reading the commit logs correctly it looks like this got in on May 26th and 0.7.3 was tagged on May 23rd? Just missed it!

Thanks for the followup, you guys rock. Srsly.

**Comment by seb-thomas** [comment] 2014-12-08 12:52
Hullo, 
sorry, chasing this bug (https://github.com/Leaflet/Leaflet/issues/2489 - think it's a bug!) round the webs. I'm using mapbox.js, does this mean it will be in 2.1.5? thanks guyz

**Comment by jfirebaugh** [comment] 2014-12-08 18:00
@sebastianthomas That fix is not yet in any released version of Leaflet so I can't say when it will appear in Mapbox.js.

**Comment by tmcw** [comment] 2016-11-17 17:45
2.4.0 uses Leaflet 0.7.7, where this version issue is fixed.

**Closed as completed by tmcw** 2016-11-17 17:45 UTC

**Comment by jmoe** [comment] 2016-11-21 16:35
👍
