### ISSUE TITLE
I can temporarily move my marker

### ISSUE THREAD

**Issue by hanagana** [mapbox/mapbox.js#1161] opened 2016-09-09 10:35 UTC
Hi Mapbox team,
I have a bug with mapboxJS when integrate within an ionic app. I can temporarily move my marker, you can see the video in the below link. What should I do to pass this bug?

Here is the video: https://drive.google.com/file/d/0B5Hg3QoOEwyYVzVJTXZCVHd2Nzg/view

Thank you for your support.
Ha Nguyen

**Comment by tmcw** [comment] 2016-10-03 13:55
Hi Ha,

Can you provide a complete example of the code that goes into this example, and also describe whether the issue is visible outside of Ionic, on a webpage or mobile web app?

Thanks,

Tom

**Comment by tmcw** [comment] 2016-11-17 17:44
Happy to debug this if you can provide code - comment back on this ticket if so. Closing for now since this isn't solvable without an interactive example.

**Closed as completed by tmcw** 2016-11-17 17:44 UTC
