### ISSUE TITLE
Move to Leaflet v1.0.0 stable

### ISSUE THREAD

**Issue by cquilboss** [mapbox/mapbox.js#1164] opened 2016-09-27 18:30 UTC
Leaflet is now stable on v1.0.0 and fix some important performance issues:
https://github.com/Leaflet/Leaflet/blob/master/CHANGELOG.md

It would be nice to upgrade mapbox.js as well ;-)

Thanks

**Comment by mourner** [comment] 2016-09-27 18:33
Yes, planning to do this! Closing as a duplicate of #1038

**Closed as completed by mourner** 2016-09-27 18:33 UTC
