### ISSUE TITLE
`zoomed` event reports indeterminate zoom level

### ISSUE THREAD

**Issue by yuvadm** [mapbox/mapbox.js#147] opened 2012-12-23 13:30 UTC
The [`zoomed` event callback](http://mapbox.com/mapbox.js/api/v0.6.7/#Event_%22zoomed%22) seems to be triggered on the start of a zoom event.
In case of an animated zoom (this is the default), the zoom reported in the callback is indeterminate.

``` js
map.addCallback("zoomed", function(map, zoomOffset) {
  console.log("Current map zoom is: ", map.zoom());
  // a value between start and end zoom level, but inconsistent
});
```

This implementation has no practical use. Zoom levels mid-transition are not reliable, and the reported `zoomOffset` does not report which zoom level it is offset _from_.

**Comment by idan** [comment] 2012-12-23 13:32
We've been over the docs and don't grok if there's a correct way to go about handling this.

**Comment by tmcw** [comment] 2013-04-23 20:26
Duplicate of #117

**Closed as completed by tmcw** 2013-04-23 20:26 UTC
